# Generated by Django 4.0.3 on 2023-05-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_adi', models.CharField(max_length=100)),
                ('foto_aciklama', models.TextField()),
                ('foto_veri', models.CharField(max_length=100)),
                ('anasayfa', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='photos.category')),
            ],
        ),
    ]
